###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

# Documentação base: https://imasters.com.br/devsecops/como-usar-o-xdebug-dentro-de-um-container-docker #
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: xdebug-docker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8200:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: xdebug-docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

